server:
  port: 9091
  servlet:
    context-path: /ms-ne-pokemon/v1
   
pokeapi:
    url: https://pokeapi.co/api/v2


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

sacavix:
  queue:
    name: cola2